apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-ref: aff75f56b150aff363c929c4236539475d3bc0d2
    app.openshift.io/vcs-uri: https://github.com/jaspaulkhurana/nextjs-sample-app
  labels:
    app: jk-nextjs-sample-app
    app.kubernetes.io/instance: jk-nextjs-sample-app
    app.kubernetes.io/name: jk-nextjs-sample-app-nextjs-sample-app
    app.openshift.io/runtime: js
  name: nextjs-sample-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: jk-nextjs-sample-app
    app.kubernetes.io/instance: jk-nextjs-sample-app
    app.kubernetes.io/name: jk-nextjs-sample-app-nextjs-sample-app
    app.openshift.io/runtime: js
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-ref: aff75f56b150aff363c929c4236539475d3bc0d2
    app.openshift.io/vcs-uri: https://github.com/jaspaulkhurana/nextjs-sample-app
  labels:
    app: jk-nextjs-sample-app
    app.kubernetes.io/instance: jk-nextjs-sample-app
    app.kubernetes.io/name: jk-nextjs-sample-app-nextjs-sample-app
    app.openshift.io/runtime: js
  name: nextjs-sample-app
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: jk-nextjs-sample-app
      app.kubernetes.io/instance: jk-nextjs-sample-app
      app.kubernetes.io/name: jk-nextjs-sample-app-nextjs-sample-app
      app.openshift.io/runtime: js
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-ref: aff75f56b150aff363c929c4236539475d3bc0d2
        app.openshift.io/vcs-uri: https://github.com/jaspaulkhurana/nextjs-sample-app
      labels:
        app: jk-nextjs-sample-app
        app.kubernetes.io/instance: jk-nextjs-sample-app
        app.kubernetes.io/name: jk-nextjs-sample-app-nextjs-sample-app
        app.openshift.io/runtime: js
    spec:
      containers:
      - env:
        - name: INGRESS_HOST
        - name: PROTOCOLS
        - name: LOG_LEVEL
          value: debug
        image: quay.io/jaspaul_khurana_ibm/nextjs-sample-app:aff75f56b150aff363c929c4236539475d3bc0d2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: nextjs-sample-app
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-ref: aff75f56b150aff363c929c4236539475d3bc0d2
    app.openshift.io/vcs-uri: https://github.com/jaspaulkhurana/nextjs-sample-app
    argocd.argoproj.io/sync-options: Validate=false
    openshift.io/host.generated: "true"
  labels:
    app: jk-nextjs-sample-app
    app.kubernetes.io/instance: jk-nextjs-sample-app
    app.kubernetes.io/name: jk-nextjs-sample-app-nextjs-sample-app
    app.openshift.io/runtime: js
  name: nextjs-sample-app
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: nextjs-sample-app
    weight: 100
  wildcardPolicy: None
