apiVersion: v1
kind: Secret
metadata:
  labels:
    app: nextjs-app
    app.kubernetes.io/instance: nextjs-app-instance
    app.kubernetes.io/name: nextjs-app
  name: postgres-credentials
stringData:
  dbhost: database.dale-nick-fahad-nextjsapp.svc
  dbname: example
  dbpassword: postgres
  dbport: "5432"
  dbuser: postgres
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nextjs-app
    app.kubernetes.io/instance: nextjs-app-instance
    app.kubernetes.io/name: nextjs-app
  name: nextjs-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: nextjs-app
    app.kubernetes.io/instance: nextjs-app-instance
    app.kubernetes.io/name: nextjs-app
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nextjs-app
    app.kubernetes.io/instance: nextjs-app-instance
    app.kubernetes.io/name: nextjs-app
    app.openshift.io/runtime: js
  name: nextjs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs-app
      app.kubernetes.io/instance: nextjs-app-instance
      app.kubernetes.io/name: nextjs-app
  template:
    metadata:
      labels:
        app: nextjs-app
        app.kubernetes.io/instance: nextjs-app-instance
        app.kubernetes.io/name: nextjs-app
    spec:
      containers:
      - env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: dbuser
              name: postgres-credentials
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: dbpassword
              name: postgres-credentials
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              key: dbhost
              name: postgres-credentials
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              key: dbport
              name: postgres-credentials
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              key: dbname
              name: postgres-credentials
        image: quay.io/dale-lane/nextjs-dale-lane:e62b2aa10750ae5297119b4a1f0ee76e507f18df
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: nextjs-app
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  labels:
    app: nextjs-app
    app.kubernetes.io/instance: nextjs-app-instance
    app.kubernetes.io/name: nextjs-app
  name: nextjs-app
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: nextjs-app
    weight: 100
  wildcardPolicy: None
