apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-ref: 1603a495948ccc7e093fdd14bc55d5e5ab6ea2b1
    app.openshift.io/vcs-uri: https://github.com/ajagup/ajay-dimitri-next-app-repo
  labels:
    app: ajay-dimitri-next-app
    app.kubernetes.io/instance: ajay-dimitri-next-app
    app.kubernetes.io/name: ajay-dimitri-next-app-ajay-dimitri-next-app
    app.openshift.io/runtime: js
  name: ajay-dimitri-next-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: ajay-dimitri-next-app
    app.kubernetes.io/instance: ajay-dimitri-next-app
    app.kubernetes.io/name: ajay-dimitri-next-app-ajay-dimitri-next-app
    app.openshift.io/runtime: js
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-ref: 1603a495948ccc7e093fdd14bc55d5e5ab6ea2b1
    app.openshift.io/vcs-uri: https://github.com/ajagup/ajay-dimitri-next-app-repo
  labels:
    app: ajay-dimitri-next-app
    app.kubernetes.io/instance: ajay-dimitri-next-app
    app.kubernetes.io/name: ajay-dimitri-next-app-ajay-dimitri-next-app
    app.openshift.io/runtime: js
  name: ajay-dimitri-next-app
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ajay-dimitri-next-app
      app.kubernetes.io/instance: ajay-dimitri-next-app
      app.kubernetes.io/name: ajay-dimitri-next-app-ajay-dimitri-next-app
      app.openshift.io/runtime: js
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-ref: 1603a495948ccc7e093fdd14bc55d5e5ab6ea2b1
        app.openshift.io/vcs-uri: https://github.com/ajagup/ajay-dimitri-next-app-repo
      labels:
        app: ajay-dimitri-next-app
        app.kubernetes.io/instance: ajay-dimitri-next-app
        app.kubernetes.io/name: ajay-dimitri-next-app-ajay-dimitri-next-app
        app.openshift.io/runtime: js
    spec:
      containers:
      - env:
        - name: INGRESS_HOST
        - name: PROTOCOLS
        - name: LOG_LEVEL
          value: debug
        image: quay.io/ajay_gup/express-sample-app:1603a495948ccc7e093fdd14bc55d5e5ab6ea2b1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: ajay-dimitri-next-app
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-ref: 1603a495948ccc7e093fdd14bc55d5e5ab6ea2b1
    app.openshift.io/vcs-uri: https://github.com/ajagup/ajay-dimitri-next-app-repo
    argocd.argoproj.io/sync-options: Validate=false
    openshift.io/host.generated: "true"
  labels:
    app: ajay-dimitri-next-app
    app.kubernetes.io/instance: ajay-dimitri-next-app
    app.kubernetes.io/name: ajay-dimitri-next-app-ajay-dimitri-next-app
    app.openshift.io/runtime: js
  name: ajay-dimitri-next-app
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: ajay-dimitri-next-app
    weight: 100
  wildcardPolicy: None
