apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-ref: 8433ebeb226560b505e7d95bbda1a6556fe662e2
    app.openshift.io/vcs-uri: https://github.com/davidbieder/fullstack-backend
  labels:
    app: david-bieder-fullstack-wip
    app.kubernetes.io/instance: david-bieder-fullstack-wip
    app.kubernetes.io/name: david-bieder-fullstack-wip-fullstack-backend
    app.openshift.io/runtime: js
  name: backend
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: david-bieder-fullstack-wip
    app.kubernetes.io/instance: david-bieder-fullstack-wip
    app.kubernetes.io/name: david-bieder-fullstack-wip-fullstack-backend
    app.openshift.io/runtime: js
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-ref: 8433ebeb226560b505e7d95bbda1a6556fe662e2
    app.openshift.io/vcs-uri: https://github.com/davidbieder/fullstack-backend
  labels:
    app: david-bieder-fullstack-wip
    app.kubernetes.io/instance: david-bieder-fullstack-wip
    app.kubernetes.io/name: david-bieder-fullstack-wip-fullstack-backend
    app.openshift.io/runtime: js
  name: backend
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: david-bieder-fullstack-wip
      app.kubernetes.io/instance: david-bieder-fullstack-wip
      app.kubernetes.io/name: david-bieder-fullstack-wip-fullstack-backend
      app.openshift.io/runtime: js
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-ref: 8433ebeb226560b505e7d95bbda1a6556fe662e2
        app.openshift.io/vcs-uri: https://github.com/davidbieder/fullstack-backend
      labels:
        app: david-bieder-fullstack-wip
        app.kubernetes.io/instance: david-bieder-fullstack-wip
        app.kubernetes.io/name: david-bieder-fullstack-wip-fullstack-backend
        app.openshift.io/runtime: js
    spec:
      containers:
      - env:
        - name: INGRESS_HOST
        - name: PROTOCOLS
        - name: LOG_LEVEL
          value: debug
        image: quay.io/davidbieder/fullstack-backend:8433ebeb226560b505e7d95bbda1a6556fe662e2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: backend
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-ref: 8433ebeb226560b505e7d95bbda1a6556fe662e2
    app.openshift.io/vcs-uri: https://github.com/davidbieder/fullstack-backend
    haproxy.router.openshift.io/rewrite-target: /
  labels:
    app: david-bieder-fullstack-wip
    app.kubernetes.io/instance: david-bieder-fullstack-wip
    app.kubernetes.io/name: david-bieder-fullstack-wip-fullstack-backend
    app.openshift.io/runtime: js
  name: backend
spec:
  host: staging-david-bieder-fullstack-wip.ibmcloud-roks-twbby-6ccd7f378ae819553d37d5f2ee142bd6-0000.eu-gb.containers.appdomain.cloud
  path: /api
  tls:
    termination: edge
  to:
    kind: Service
    name: backend
    weight: 100
  wildcardPolicy: None
