apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-ref: a97841daa9cab62317581b25278e686d7ba3a6b4
    app.openshift.io/vcs-uri: https://github.com/SamChinellato/express-sample-app
    appls: ""
  labels:
    app: sam-chinellato-tekton-triggers
    app.kubernetes.io/instance: sam-chinellato-tekton-triggers
    app.kubernetes.io/name: sam-chinellato-tekton-triggers-express-sample-app
    app.openshift.io/runtime: js
  name: express-sample-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: sam-chinellato-tekton-triggers
    app.kubernetes.io/instance: sam-chinellato-tekton-triggers
    app.kubernetes.io/name: sam-chinellato-tekton-triggers-express-sample-app
    app.openshift.io/runtime: js
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-ref: a97841daa9cab62317581b25278e686d7ba3a6b4
    app.openshift.io/vcs-uri: https://github.com/SamChinellato/express-sample-app
    appls: ""
  labels:
    app: sam-chinellato-tekton-triggers
    app.kubernetes.io/instance: sam-chinellato-tekton-triggers
    app.kubernetes.io/name: sam-chinellato-tekton-triggers-express-sample-app
    app.openshift.io/runtime: js
  name: express-sample-app
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sam-chinellato-tekton-triggers
      app.kubernetes.io/instance: sam-chinellato-tekton-triggers
      app.kubernetes.io/name: sam-chinellato-tekton-triggers-express-sample-app
      app.openshift.io/runtime: js
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-ref: a97841daa9cab62317581b25278e686d7ba3a6b4
        app.openshift.io/vcs-uri: https://github.com/SamChinellato/express-sample-app
        appls: ""
      labels:
        app: sam-chinellato-tekton-triggers
        app.kubernetes.io/instance: sam-chinellato-tekton-triggers
        app.kubernetes.io/name: sam-chinellato-tekton-triggers-express-sample-app
        app.openshift.io/runtime: js
    spec:
      containers:
      - env:
        - name: INGRESS_HOST
        - name: PROTOCOLS
        - name: LOG_LEVEL
          value: debug
        image: quay.io/samchinellato/demo-express-app:a97841daa9cab62317581b25278e686d7ba3a6b4
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: express-sample-app
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-ref: a97841daa9cab62317581b25278e686d7ba3a6b4
    app.openshift.io/vcs-uri: https://github.com/SamChinellato/express-sample-app
    appls: ""
    argocd.argoproj.io/sync-options: Validate=false
    openshift.io/host.generated: "true"
  labels:
    app: sam-chinellato-tekton-triggers
    app.kubernetes.io/instance: sam-chinellato-tekton-triggers
    app.kubernetes.io/name: sam-chinellato-tekton-triggers-express-sample-app
    app.openshift.io/runtime: js
  name: express-sample-app
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: express-sample-app
    weight: 100
  wildcardPolicy: None
