apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-ref: 3d89aafde960a575837fb14b740cdd8bf90eb12c
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/matt-eugen-next-app
  labels:
    app: matt-eugen-tekton-e2e-assignment
    app.kubernetes.io/instance: matt-eugen-tekton-e2e-assignment
    app.kubernetes.io/name: matt-eugen-tekton-e2e-assignment-next-e2e-app
    app.openshift.io/runtime: js
  name: nextjs-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: matt-eugen-tekton-e2e-assignment
    app.kubernetes.io/instance: matt-eugen-tekton-e2e-assignment
    app.kubernetes.io/name: matt-eugen-tekton-e2e-assignment-next-e2e-app
    app.openshift.io/runtime: js
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-ref: 3d89aafde960a575837fb14b740cdd8bf90eb12c
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/matt-eugen-next-app
  labels:
    app: matt-eugen-tekton-e2e-assignment
    app.kubernetes.io/instance: matt-eugen-tekton-e2e-assignment
    app.kubernetes.io/name: matt-eugen-tekton-e2e-assignment-next-e2e-app
    app.openshift.io/runtime: js
  name: nextjs-app
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: matt-eugen-tekton-e2e-assignment
      app.kubernetes.io/instance: matt-eugen-tekton-e2e-assignment
      app.kubernetes.io/name: matt-eugen-tekton-e2e-assignment-next-e2e-app
      app.openshift.io/runtime: js
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-ref: 3d89aafde960a575837fb14b740cdd8bf90eb12c
        app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/matt-eugen-next-app
      labels:
        app: matt-eugen-tekton-e2e-assignment
        app.kubernetes.io/instance: matt-eugen-tekton-e2e-assignment
        app.kubernetes.io/name: matt-eugen-tekton-e2e-assignment-next-e2e-app
        app.openshift.io/runtime: js
    spec:
      containers:
      - env:
        - name: INGRESS_HOST
        - name: PROTOCOLS
        - name: LOG_LEVEL
          value: debug
        image: quay.io/matthewparry/next-e2e-app:3d89aafde960a575837fb14b740cdd8bf90eb12c
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: nextjs-app
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-ref: 3d89aafde960a575837fb14b740cdd8bf90eb12c
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/matt-eugen-next-app
    argocd.argoproj.io/sync-options: Validate=false
    openshift.io/host.generated: "true"
  labels:
    app: matt-eugen-tekton-e2e-assignment
    app.kubernetes.io/instance: matt-eugen-tekton-e2e-assignment
    app.kubernetes.io/name: matt-eugen-tekton-e2e-assignment-next-e2e-app
    app.openshift.io/runtime: js
  name: nextjs-app
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: nextjs-app
    weight: 100
  wildcardPolicy: None
