apiVersion: v1
kind: Service
metadata:
  labels:
    app: express-app
    app.kubernetes.io/instance: express-app-instance
    app.kubernetes.io/name: express-app
  name: express-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: express-app
    app.kubernetes.io/instance: express-app-instance
    app.kubernetes.io/name: express-app
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: express-app
    app.kubernetes.io/instance: express-app-instance
    app.kubernetes.io/name: express-app
    app.openshift.io/runtime: js
  name: express-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-app
      app.kubernetes.io/instance: express-app-instance
      app.kubernetes.io/name: express-app
  template:
    metadata:
      labels:
        app: express-app
        app.kubernetes.io/instance: express-app-instance
        app.kubernetes.io/name: express-app
    spec:
      containers:
      - env:
        - name: DEBUG
          value: myapp:*
        image: quay.io/dale-lane/express-dale-lane:1b5a2f1728a6c62b4f56eeadd89989f64ffcb627
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: express-app
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  labels:
    app: express-app
    app.kubernetes.io/instance: express-app-instance
    app.kubernetes.io/name: express-app
  name: express-app
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: express-app
    weight: 100
  wildcardPolicy: None
